### ISSUE TITLE
`mod2pi` may return negative numbers

### ISSUE THREAD

**Issue by alion02** [VirxEC/dubins_paths#1]
The documentation states that the `mod2pi` function transforms the given value so that it falls in the range [0, 2pi), but the below code panics.
```rust
assert!(mod2pi(-f32::from_bits(1)) >= 0.);
```
This is caused by insufficient leftover precision to carry out the division by 2pi without rounding to 0.

**Comment by VirxEC** [comment]
This largest value this is a problem with is `-f32::from_bits(3)`; `-f32::from_bits(4)` works fine. I am not smart enough to fix this issue, but thanks for bringing it to my attention. Maybe google will have an answer.

**Comment by alion02** [comment]
I think you're looking for [`rem_euclid`](https://doc.rust-lang.org/std/primitive.f32.html#method.rem_euclid).
